import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import restapiSidebar from "./docs/rest-api/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'quick-start',
    {
      type: "category",
      label: "User Guide",
      collapsed: false,
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide',
        },
      ]
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ]
    },
    {
      type: "category",
      label: "Developer Guide",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer-guide',
        },
      ]
    },
    {
      type: "category",
      label: "Architecture",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ]
    },
    {
      type: "category",
      label: "REST API",
      link: {
        type: "generated-index",
        title: "REST API",
        description:
          "This is the documentation for the OpenRemote Manager HTTP REST API.",
        slug: "/category/rest-api",
      },
      items: restapiSidebar.sort((a, b) => {
        if (a.label === "Schemas") {
          return 1;
        }
        else {
          return (a.label ?? '').localeCompare(b.label ?? '')
        }
      }),
    },
    {
      type: 'link',
      label: 'JavaDoc',
      href: 'https://www.javadoc.io/doc/io.openremote',
    },
 ],
};

export default sidebars;
