import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "rest-api/openremote-manager-rest-api",
    },
    {
      type: "category",
      label: "Agent",
      link: {
        type: "doc",
        id: "rest-api/agent",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/do-protocol-asset-discovery",
          label: "Do protocol asset discovery",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/do-protocol-asset-import",
          label: "Do protocol asset import",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/do-protocol-instance-discovery",
          label: "Do protocol instance discovery",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Alarm",
      link: {
        type: "doc",
        id: "rest-api/alarm",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-alarms",
          label: "Retrieve all alarms or a subset using filter criteria",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/create-alarm",
          label: "Create an alarm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/remove-alarms",
          label: "Remove alarms",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-alarm",
          label: "Retrieve an alarm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-alarm",
          label: "Update an alarm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/remove-alarm",
          label: "Remove an alarm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-asset-links",
          label: "Retrieve the asset links of an alarm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/set-asset-links",
          label: "Set the asset links of an alarm",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      link: {
        type: "doc",
        id: "rest-api/configuration",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/file-upload",
          label: "Upload a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/update-configuration",
          label: "Update manager configuration",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "UI Apps",
      link: {
        type: "doc",
        id: "rest-api/ui-apps",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-app-infos",
          label: "Retrieve the info of the available applications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-apps",
          label: "Retrieve a list of the available applications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-console-config",
          label: "Retrieve the console configuration",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Asset Model",
      link: {
        type: "doc",
        id: "rest-api/asset-model",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-asset-descriptors",
          label: "Retrieve the available asset descriptors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-asset-info",
          label: "Retrieve the asset type information of an asset type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-asset-infos",
          label: "Retrieve the asset type information of each available asset type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-meta-item-descriptors",
          label: "Retrieve the available meta item descriptors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-value-descriptors",
          label: "Retrieve the available value descriptors",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Asset",
      link: {
        type: "doc",
        id: "rest-api/asset",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/create-asset",
          label: "Create an asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/delete-asset",
          label: "Delete assets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-user-asset-links",
          label: "Retrieve links between assets and users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/create-user-asset-links",
          label: "Create links between users and assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/delete-all-user-asset-links",
          label: "Delete all user asset links",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/delete-user-asset-link",
          label: "Delete a link between an asset and user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/delete-user-asset-links",
          label: "Delete user asset links",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/get-asset",
          label: "Retrieve an asset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-asset",
          label: "Update an asset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-current-user-assets",
          label: "Retrieve the linked assets of the currently authenticated user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-partial-asset",
          label: "Retrieve a partially loaded asset (no attributes or path)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/query-assets",
          label: "Retrieve assets using a query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/delete-assets-parent",
          label: "Delete the parent of assets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/update-asset-parent",
          label: "Update the parent of assets",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/write-attribute-value",
          label: "Write to a single attribute",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/write-attribute-values",
          label: "Update attribute values",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Console",
      link: {
        type: "doc",
        id: "rest-api/console",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/register",
          label: "Create or update the registration for a console",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      link: {
        type: "doc",
        id: "rest-api/dashboard",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/update-dashboard",
          label: "Update a dashboard",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/create-dashboard",
          label: "Create a dashboard",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/get-dashboard",
          label: "Retrieve a dashboard",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/delete-dashboard",
          label: "Delete a dashboard",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-all-realm-dashboards",
          label: "Retrieve all accessible dashboards",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/query-dashboards",
          label: "Retrieve dashboards using a query",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Asset Datapoint",
      link: {
        type: "doc",
        id: "rest-api/asset-datapoint",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-datapoint-export",
          label: "Retrieve a datapoint export of an asset attribute",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-datapoint-period",
          label: "Retrieve a datapoint period of an asset attribute",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-datapoints",
          label: "Retrieve the historical datapoints of an asset attribute",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Asset Predicted Datapoint",
      link: {
        type: "doc",
        id: "rest-api/asset-predicted-datapoint",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/write-predicted-datapoints",
          label: "Write the predicted datapoints of an asset attribute",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-predicted-datapoints",
          label: "Retrieve the predicted datapoints of an asset attribute",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Gateway",
      link: {
        type: "doc",
        id: "rest-api/gateway",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-connection",
          label: "Retrieve the gateway connection of a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/set-connection",
          label: "Update the gateway connection of a realm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/delete-connection",
          label: "Delete the gateway connection of a realm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-connections",
          label: "Retrieve the gateway connections of all realms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/delete-connections",
          label: "Delete the gateway connections of multiple realms",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-connection-status",
          label: "Retrieve the gateway connection status of a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-active-tunnel-info",
          label: "Retrieve the gateway tunnel information of tunnel for a gateway in a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-all-active-tunnel-infos",
          label: "Retrieve all active gateway tunnel information of a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-gateway-active-tunnel-infos",
          label: "Retrieve the active gateway tunnel information of gateway in a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/start-tunnel",
          label: "Start a tunnel for a gateway",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/stop-tunnel",
          label: "Stop a tunnel for a gateway",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Map",
      link: {
        type: "doc",
        id: "rest-api/map",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-settings",
          label: "Retrieve the style used for Mapbox GL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/save-settings",
          label: "Update map settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-settings-js",
          label: "Retrieve the tileJSON object used for Mapbox GL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-tile",
          label: "Retrieve the vector tile data for Mapbox GL",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Notification",
      link: {
        type: "doc",
        id: "rest-api/notification",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-notifications",
          label: "Retrieve all sent notifications by targets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/remove-notifications",
          label: "Delete all sent notifications by targets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/notification-acknowledged",
          label: "Update a notification as acknowledged",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/notification-delivered",
          label: "Update a notification as delivered",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/remove-notification",
          label: "Delete a sent notification",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/send-notification",
          label: "Send a notification to one or more targets",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Provisioning",
      link: {
        type: "doc",
        id: "rest-api/provisioning",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-provisioning-configs",
          label: "Retrieve all provisioning configurations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/create-provisioning-config",
          label: "Create a provisioning configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/update-provisioning-config",
          label: "Update a provisioning configuration",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/delete-provisioning-config",
          label: "Delete a provisioning configuration",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Rule",
      link: {
        type: "doc",
        id: "rest-api/rule",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/create-asset-ruleset",
          label: "Create an asset ruleset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/get-global-rulesets",
          label: " Retrieve the global rules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/create-global-ruleset",
          label: "Create a global ruleset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/create-realm-ruleset",
          label: "Create a realm ruleset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/get-asset-ruleset",
          label: "Retrieve an asset ruleset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-asset-ruleset",
          label: "Update an asset ruleset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/delete-asset-ruleset",
          label: "Delete an asset ruleset",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-global-ruleset",
          label: "Retrieve a global ruleset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-global-ruleset",
          label: "Update a global ruleset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/delete-global-ruleset",
          label: "Delete a global ruleset",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-realm-ruleset",
          label: "Retrieve a realm ruleset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-realm-ruleset",
          label: "Update a realm ruleset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/delete-realm-ruleset",
          label: "Delete a realm ruleset",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-asset-engine-info",
          label: "Retrieve information about an asset rules engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-asset-geofences",
          label: "Get the geofences of an asset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-asset-rulesets",
          label: "Retrieve the rules of an asset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-global-engine-info",
          label: "Retrieve information about the global rules engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-realm-engine-info",
          label: "Retrieve information about a realm rules engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-realm-rulesets",
          label: "Retrieve the rules of a realm",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Flow",
      link: {
        type: "doc",
        id: "rest-api/flow",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-all-node-definitions",
          label: "Retrieve all node definitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-all-node-definitions-by-type",
          label: "Retrieve all node definitions by type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-node-definition",
          label: "Retrieve a node definition by name",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Realm",
      link: {
        type: "doc",
        id: "rest-api/realm",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-all-realms",
          label: "Retrieve all realms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/create-realm",
          label: "Create a new realm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/get-realm",
          label: "Retrieve details about the currently authenticated and active realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-realm",
          label: "Update a realm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/delete-realm",
          label: "Delete a realm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-accessible-realms",
          label: "Retrieve accessible realms for the authenticated user",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "User",
      link: {
        type: "doc",
        id: "rest-api/user",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/update-user",
          label: "Update a user in a realm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/create-user",
          label: "Create a new user in a realm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/delete-user",
          label: "Delete a user from a realm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/disconnect-user-session",
          label: "Disconnect a user session using a session ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-user",
          label: "Retrieve a user in a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-client-roles",
          label: "Retrieve client roles for a realm and client",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-client-roles",
          label: "Update client roles for a realm and client",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-current-user",
          label: "Retrieve the currently authenticated user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-current-user-client-roles",
          label: "Retrieve client roles for the currently authenticated user using a client ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-current-user-realm-roles",
          label: "Retrieve realm roles for the currently authenticated user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-current-user-roles",
          label: "Retrieve client roles for the currently authenticated user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-roles",
          label: "Retrieve roles for a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-roles",
          label: "Update roles for a realm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-user-client-roles",
          label: "Retrieve client roles for a user using a client ID in a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-user-client-roles",
          label: "Update client roles for a user in a realm using a client ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-user-realm-roles",
          label: "Retrieve realm roles for a user in a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-user-realm-roles",
          label: "Update realm roles for a user in a realm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-user-roles",
          label: "Retrieve client roles for a user in a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-user-roles",
          label: "Update client roles for a user in a realm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/get-user-sessions",
          label: "Retrieve sessions for a user in a realm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/query-users",
          label: "Query users based on criteria",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/reset-password",
          label: "Reset the password for a user in a realm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/reset-secret",
          label: "Reset the secret for a user in a realm",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Syslog",
      link: {
        type: "doc",
        id: "rest-api/syslog",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-events",
          label: "Retrieve the syslog events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/clear-events",
          label: "Clear the syslog events",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/get-config",
          label: "Retrieve the syslog configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/update-config",
          label: "Update the syslog configuration",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Status",
      link: {
        type: "doc",
        id: "rest-api/status",
      },
      items: [
        {
          type: "doc",
          id: "rest-api/get-health-status",
          label: "Retrieve the health status of the system",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/get-info",
          label: "Retrieve the system information",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "rest-api/schemas/allowedvalues",
          label: "AllowedValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetobject",
          label: "AssetObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assettreenode",
          label: "AssetTreeNode",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributemap",
          label: "AttributeMap",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributeobject",
          label: "AttributeObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/future",
          label: "Future",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/futureorpresent",
          label: "FutureOrPresent",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/max",
          label: "Max",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/metaitemobject",
          label: "MetaItemObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/metamap",
          label: "MetaMap",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/min",
          label: "Min",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/notblank",
          label: "NotBlank",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/notempty",
          label: "NotEmpty",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/notnull",
          label: "NotNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/past",
          label: "Past",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/pastorpresent",
          label: "PastOrPresent",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/pattern",
          label: "Pattern",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/size",
          label: "Size",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/valueconstraint",
          label: "ValueConstraint",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/valuedescriptorobject",
          label: "ValueDescriptorObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/valueformat",
          label: "ValueFormat",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/fileinfo",
          label: "FileInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/agentobjectobjectobject",
          label: "AgentObjectObjectObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/sentalarm",
          label: "SentAlarm",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/alarm",
          label: "Alarm",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/alarmassetlink",
          label: "AlarmAssetLink",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/id",
          label: "Id",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/agentdescriptor",
          label: "AgentDescriptor",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetdescriptorobject",
          label: "AssetDescriptorObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assettypeinfo",
          label: "AssetTypeInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributedescriptorobject",
          label: "AttributeDescriptorObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/metaitemdescriptorobject",
          label: "MetaItemDescriptorObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/userassetlink",
          label: "UserAssetLink",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/arraypredicate",
          label: "ArrayPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetquery",
          label: "AssetQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributepredicate",
          label: "AttributePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/booleanpredicate",
          label: "BooleanPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/calendareventpredicate",
          label: "CalendarEventPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/datetimepredicate",
          label: "DateTimePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/logicgroupattributepredicate",
          label: "LogicGroupAttributePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/namevaluepredicate",
          label: "NameValuePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/numberpredicate",
          label: "NumberPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/orderby",
          label: "OrderBy",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/parentpredicate",
          label: "ParentPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/pathpredicate",
          label: "PathPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/radialgeofencepredicate",
          label: "RadialGeofencePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/realmpredicate",
          label: "RealmPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/rectangulargeofencepredicate",
          label: "RectangularGeofencePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/select",
          label: "Select",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/stringpredicate",
          label: "StringPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/valueanypredicate",
          label: "ValueAnyPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/valueemptypredicate",
          label: "ValueEmptyPredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/valuepredicate",
          label: "ValuePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributeref",
          label: "AttributeRef",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributewriteresult",
          label: "AttributeWriteResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributestate",
          label: "AttributeState",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/consoleprovider",
          label: "ConsoleProvider",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/consoleregistration",
          label: "ConsoleRegistration",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/dashboard",
          label: "Dashboard",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/dashboardgriditem",
          label: "DashboardGridItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/dashboardscreenpreset",
          label: "DashboardScreenPreset",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/dashboardtemplate",
          label: "DashboardTemplate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/dashboardwidget",
          label: "DashboardWidget",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetconditions",
          label: "AssetConditions",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/conditions",
          label: "Conditions",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/dashboardconditions",
          label: "DashboardConditions",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/dashboardquery",
          label: "DashboardQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/datapointperiod",
          label: "DatapointPeriod",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/valuedatapointobject",
          label: "ValueDatapointObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetdatapointallquery",
          label: "AssetDatapointAllQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetdatapointintervalquery",
          label: "AssetDatapointIntervalQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetdatapointlttbquery",
          label: "AssetDatapointLTTBQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetdatapointquery",
          label: "AssetDatapointQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/gatewayattributefilter",
          label: "GatewayAttributeFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/gatewayconnection",
          label: "GatewayConnection",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/gatewaytunnelinfo",
          label: "GatewayTunnelInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/objectnode",
          label: "ObjectNode",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/geojsonconfig",
          label: "GeoJsonConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/maprealmconfig",
          label: "MapRealmConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/abstractnotificationmessage",
          label: "AbstractNotificationMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/emailnotificationmessage",
          label: "EmailNotificationMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/pushnotificationaction",
          label: "PushNotificationAction",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/pushnotificationbutton",
          label: "PushNotificationButton",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/pushnotificationmessage",
          label: "PushNotificationMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/recipient",
          label: "Recipient",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/sentnotification",
          label: "SentNotification",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/jsonnode",
          label: "JsonNode",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/notification",
          label: "Notification",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/target",
          label: "Target",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/provisioningconfigobjectobject",
          label: "ProvisioningConfigObjectObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/x-509-provisioningconfig",
          label: "X509ProvisioningConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/x-509-provisioningdata",
          label: "X509ProvisioningData",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/assetruleset",
          label: "AssetRuleset",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/globalruleset",
          label: "GlobalRuleset",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/realmruleset",
          label: "RealmRuleset",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/rulesengineinfo",
          label: "RulesEngineInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/geofencedefinition",
          label: "GeofenceDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/node",
          label: "Node",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/nodeinternal",
          label: "NodeInternal",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/nodeposition",
          label: "NodePosition",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/nodesocket",
          label: "NodeSocket",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/option",
          label: "Option",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/picker",
          label: "Picker",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/realm",
          label: "Realm",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/realmrole",
          label: "RealmRole",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/usersession",
          label: "UserSession",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/attributevaluepredicate",
          label: "AttributeValuePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/userquery",
          label: "UserQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/credential",
          label: "Credential",
          className: "schema",
        },
        {
          type: "doc",
          id: "rest-api/schemas/syslogconfig",
          label: "SyslogConfig",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
